name: Build WAR File

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13.x
      uses: actions/setup-java@v1
      with:
        java-version: '13.x'
    - name: Get Database Details
      run: |
        /usr/bin/curl --header "Authorization: token ${{ secrets.TOKEN }}" \
        --header "Accept: application/vnd.github.v3.raw" \
         --remote-name \
          --location https://api.github.com/repos/AshishBhoi/private/contents/DBDetails.java
    - name: Move Everything to Correct Places
      run: mv DBDetails.java src/util/
    - name: Build .war with Ant
      run: ant war
