name: Build WAR File

on: [push]

jobs:
  job_1:
    name: JAVA 13
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13.x
      uses: actions/setup-java@v1
      with:
        java-version: '13.x'
    - name: Get Database Details
      run: |
        /usr/bin/curl --header "Authorization: token ${{ secrets.TOKEN }}" \
        --header "Accept: application/vnd.github.v3.raw" \
         --remote-name \
          --location https://api.github.com/repos/AshishBhoi/private/contents/DBDetails.java
    - name: Move Everything to Correct Places
      run: mv DBDetails.java src/util/
    - name: Build .war with Ant
      run: ant
    - name: Save WAR File
      uses: actions/upload-artifact@v1
      with:
          name: GroupProject-1-13
          path: dist/GroupProject-1.war
  jobs_2:
    name: JAVA 12
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12.x
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Get Database Details
      run: |
        /usr/bin/curl --header "Authorization: token ${{ secrets.TOKEN }}" \
        --header "Accept: application/vnd.github.v3.raw" \
         --remote-name \
          --location https://api.github.com/repos/AshishBhoi/private/contents/DBDetails.java
    - name: Move Everything to Correct Places
      run: mv DBDetails.java src/util/
    - name: Build .war with Ant
      run: ant
    - name: Save WAR File
      uses: actions/upload-artifact@v1
      with:
          name: GroupProject-1-12
          path: dist/GroupProject-1.war
  jobs_3:
    name: JAVA 11
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11.x
      uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - name: Get Database Details
      run: |
        /usr/bin/curl --header "Authorization: token ${{ secrets.TOKEN }}" \
        --header "Accept: application/vnd.github.v3.raw" \
         --remote-name \
          --location https://api.github.com/repos/AshishBhoi/private/contents/DBDetails.java
    - name: Move Everything to Correct Places
      run: mv DBDetails.java src/util/
    - name: Build .war with Ant
      run: ant
    - name: Save WAR File
      uses: actions/upload-artifact@v1
      with:
          name: GroupProject-1-11
          path: dist/GroupProject-1.war
  jobs_4:
    name: JAVA 1.8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get Database Details
      run: |
        /usr/bin/curl --header "Authorization: token ${{ secrets.TOKEN }}" \
        --header "Accept: application/vnd.github.v3.raw" \
         --remote-name \
          --location https://api.github.com/repos/AshishBhoi/private/contents/DBDetails.java
    - name: Move Everything to Correct Places
      run: mv DBDetails.java src/util/
    - name: Build .war with Ant
      run: ant
    - name: Save WAR File
      uses: actions/upload-artifact@v1
      with:
          name: GroupProject-1-1.8
          path: dist/GroupProject-1.war
